### PR TITLE
Pebble

### PR DESCRIPTION
**Pull request by faddat**
This pebble code came from here:

https://github.com/baabeetaa/tm-db/tree/pebble

And is a great starting point.  

But kind of updating everything from here so we start from the right place. 

So:

* pebble
* gorocksdb -> grocksdb
* Dockerfile
* Remove remotedb 
* add a .vscode folder containing build tags because it's a stumbling block for this repo specifically

### CODE REVIEW

**Comment by marbar3778** [comment]
could you separate this into a few prs. this is too big to review

**Comment by faddat** [comment]
Sure.  moment while I make sure it's working....

**Comment by faddat** [comment]
Honestly, you may want to merge this one.

https://github.com/cosmos/cosmos-db/runs/7888143073?check_suite_focus=true

**Comment by marbar3778** [comment]
sam here with conflicts

**Comment by faddat** [comment]
It could cause more conflicts, but merging the newer PR's first will further reduce the scope of this one.

Happy to resolve e'm again if need be.

**Comment by marbar3778** [comment]
@faddat can you resolve conflicts

**Comment by faddat** [comment]
yep happy to

**Review by marbar3778 — APPROVED** [review]

**Pull request merged**
