### PR TITLE
remove remotedb

### PR DESCRIPTION
**Pull request by faddat**
The docs folder isn't relevant anymore, we can add some 
release info that begins at 1.0 to Readme.md.

Remotedb added many imports to this library, and 
removing it reduces the total amount of code here 
significantly while reducing the matienance burden. 

The before and after on go.mod is pretty telling:

```go
require (
	github.com/cosmos/gorocksdb v1.2.0
	github.com/dgraph-io/badger/v3 v3.2103.2
	github.com/gogo/protobuf v1.3.2
	github.com/google/btree v1.1.2
	github.com/jmhodges/levigo v1.0.0
	github.com/stretchr/testify v1.8.0
	github.com/syndtr/goleveldb v1.0.1-0.20200815110645-5c35d600f0ca
	go.etcd.io/bbolt v1.3.6
	google.golang.org/grpc v1.48.0
)

require (
	github.com/cespare/xxhash v1.1.0 // indirect
	github.com/cespare/xxhash/v2 v2.1.1 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/dgraph-io/ristretto v0.1.0 // indirect
	github.com/dustin/go-humanize v1.0.0 // indirect
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
	github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/golang/snappy v0.0.3 // indirect
	github.com/google/flatbuffers v1.12.1 // indirect
	github.com/klauspost/compress v1.12.3 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	go.opencensus.io v0.22.5 // indirect
	golang.org/x/net v0.0.0-20201021035429-f5854403a974 // indirect
	golang.org/x/sys v0.0.0-20220227234510-4e6760a101f9 // indirect
	golang.org/x/text v0.3.3 // indirect
	google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

becomes

```go

module github.com/cosmos/cosmos-db

go 1.19

require (
	github.com/cosmos/gorocksdb v1.2.0
	github.com/google/btree v1.1.2
	github.com/jmhodges/levigo v1.0.0
	github.com/stretchr/testify v1.8.0
	github.com/syndtr/goleveldb v1.0.1-0.20200815110645-5c35d600f0ca
)

require (
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/golang/snappy v0.0.3 // indirect
	github.com/kr/pretty v0.1.0 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	golang.org/x/net v0.0.0-20201021035429-f5854403a974 // indirect
	golang.org/x/sys v0.0.0-20220227234510-4e6760a101f9 // indirect
	gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

By removing remotedb, we end up with a very clear set of upstream dependencies.

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]

**Comment by marbar3778** [comment]
@faddat could you resolve conflicts

**Comment by faddat** [comment]
🔥

**Review by marbar3778 — APPROVED** [review]

**Comment by marbar3778** [comment]
@faddat can you fix this then we merge and prepare a release

**Comment by faddat** [comment]
Yep-- I also want to do a cleanup

**Pull request merged**
