### PR TITLE
grocksdb

### PR DESCRIPTION
**Pull request by faddat**
This PR:

* uses the docker image hosted at ghcr.io/cosmos/cosmos-db/build-test
* changes to a rocksdb library that can use the latest version of rocksdb, allowing meaningful performance comparisons to occur

Post-merge, we can use the docker image that this repo builds for all dev work pertaining to this repo.

### CODE REVIEW

**Comment by faddat** [comment]
@marbar3778 if I fix the build here, this branch will contain most of the changes in #5

**Comment by faddat** [comment]
small enough?

**Comment by marbar3778** [comment]
@faddat could you resolve conflicts please

**Comment by faddat** [comment]
happily!

**Comment by faddat** [comment]
This one next, so we can use the new docker image

**Review by marbar3778 — COMMENTED** [review]
I think this has changes already in main, could you rebase

**Comment by faddat** [comment]
happy to.

**Pull request closed without merging**
